version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./serverLogistica
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./clientLogistica
      dockerfile: Dockerfile
    depends_on: 
      - backend
    ports:
      - "5173:5173"
